### ISSUE TITLE
How about adding contact information?

### ISSUE THREAD

**Issue by khanchi97** [CodeClubSMVDU/gsoc-proposals#6]
I think we should also add some contact information. So that if someone wants to contact anyone from this list of selected gsoc students and in case if they need some help then it would help.

**Comment by sandeepsajan0** [comment]
@khanchi97  Contact information is already provided in proposals like Gmail and etc.

**Comment by khanchi97** [comment]
Oh, I forgot about that :smile: 
But, may be if could be better to add contact information in README.md 
It was just a suggestion (Closing it for now)
